name: sd_backend
channels:
  - pytorch
  - conda-forge
dependencies: 
  - git
  - python==3.10.5
  - pip==22.2.2

  - pytorch

  - numpy==1.23.2
  - setuptools
  - pip:
    - -e .
    - torchvision
    - torchaudio
    - pytorch-lightning==1.4.2
    - torchmetrics==0.6.0
    - PySoundFile
    - flask-socketio
    - git+https://github.com/harmonai-org/sample-generator.git#egg=audio_diffusion
    - git+https://github.com/crowsonkb/v-diffusion-pytorch.git#egg=v-diffusion-pytorch
variables:
  PYTORCH_ENABLE_MPS_FALLBACK: 1