name: dd2
channels:
  - pytorch
  - conda-forge
dependencies: 
  - git
  - pip=22.2.2
  - python=3.10.5
  - setuptools
  - pytorch
  - torchaudio
  - torchvision
  - pip:
    - -e .
    - flask-socketio
    - py-cord
    - python-dotenv
    - black
    - git+https://github.com/harmonai-org/sample-generator.git@5e2257ba285408e08b5b9e77fa9cd7791b9e223b#egg=sample_generator
variables:
  PYTORCH_ENABLE_MPS_FALLBACK: 1