name: sd_backend
channels:
  - pytorch-nightly
  - conda-forge
dependencies: 
  - git
  - pip=22.2.2
  - python=3.10.5
  - setuptools
  - pytorch
  - torchaudio
  - torchvision
  - pip:
    - -e .
    - flask-socketio
    - py-cord
    - python-dotenv
    - git+https://github.com/harmonai-org/sample-generator.git#egg=sample_generator
    - git+https://github.com/crowsonkb/v-diffusion-pytorch.git#egg=v-diffusion-pytorch
variables:
  PYTORCH_ENABLE_MPS_FALLBACK: 1