name: sd_backend
channels:
  - pytorch
  - defaults
dependencies: 
  - git
  - flask
  - python=3.8.5
  - pip=20.3
  - cudatoolkit=11.3
  - pytorch=1.11.0
  - torchvision=0.12.0
  - numpy=1.19.2
  - torchaudio
  - setuptools
  - pip:
    - -e .
    - pytorch-lightning==1.4.2
    - torchmetrics==0.6.0
    - PySoundFile
    - flask-socketio
    - py-cord
    - python-dotenv
    - black
    - git+https://github.com/harmonai-org/sample-generator.git@5e2257ba285408e08b5b9e77fa9cd7791b9e223b#egg=sample-generator
    - git+https://github.com/crowsonkb/v-diffusion-pytorch.git@987f8985e38208345c1959b0ea767a625831cc9b#egg=v-diffusion-pytorch